# Generated by Django 5.2 on 2025-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(default='new', max_length=50, verbose_name='Код'),
        ),
    ]
