# Generated by Django 5.2 on 2025-04-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proekt', '0003_remove_role_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default='Пользователь', on_delete=django.db.models.deletion.CASCADE, to='proekt.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proekt.order_table', verbose_name='Товар'),
        ),
    ]
