# Generated by Django 5.2 on 2025-04-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proekt', '0004_alter_customuser_role_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proekt.role', verbose_name='Роль'),
        ),
    ]
